name: Build Portable Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download WinPython
        run: |
          $url = "https://github.com/winpython/winpython/releases/download/3.10.11.0/Winpython64-3.10.11.0dot.exe"
          $output = "WinPython.exe"
          Invoke-WebRequest -Uri $url -OutFile $output

      - name: Extract WinPython
        run: |
          Start-Process -FilePath "WinPython.exe" -ArgumentList "-y" -Wait
          Rename-Item -Path "WPy64-31011" -NewName "python-3.10.11.amd64"

      - name: Install Dependencies
        run: |
          .\python-3.10.11.amd64\python.exe -m pip install openpyxl

      - name: Create Portable Package
        run: |
          Compress-Archive -Path "csv_limiter_gui.py", "run_csv_editor.bat", "README.md", "python-3.10.11.amd64" -DestinationPath "CSVEditor-Portable.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: CSVEditor-Portable.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
